### ISSUE TITLE
Fehler beim Starten von Services: Java command  wasn't configured yet

### ISSUE THREAD

**Issue by danzelgeb** [theSimpleCloud/SimpleCloud#135]
I've got this Error, when I start my Proxy Srervice:
`[17:00:22] [SEVERE ] java.lang.IllegalArgumentException: The java command for this name wasn't configured yet.
	at eu.thesimplecloud.base.wrapper.process.CloudServiceProcess.getStartCommandArgs(CloudServiceProcess.kt:173)
	at eu.thesimplecloud.base.wrapper.process.CloudServiceProcess.createProcessBuilder(CloudServiceProcess.kt:162)
	at eu.thesimplecloud.base.wrapper.process.CloudServiceProcess.start(CloudServiceProcess.kt:76)
	at eu.thesimplecloud.base.wrapper.process.queue.CloudServiceProcessQueue$startThread$1$1.invoke(CloudServiceProcessQueue.kt:67)
	at eu.thesimplecloud.base.wrapper.process.queue.CloudServiceProcessQueue$startThread$1$1.invoke(CloudServiceProcessQueue.kt:67)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
`

**Comment by FllipEis** [comment]
Looks like your java command wasn't configured correctly. If you're still experiencing this issue, please reopen it or create another one
