### ISSUE TITLE
Error at Paper 1.20.1 SimpleCloud-NPC startup

### ISSUE THREAD

**Issue by BadPackage** [theSimpleCloud/SimpleCloud#162]
```
[Lobby-1][22:39:16 WARN]: [SimpleCloud-NPC] Task #12 for SimpleCloud-NPC v1.0 generated an exception
[Lobby-1]java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
[Lobby-1]       at com.github.juliarn.npclib.bukkit.util.BukkitPlatformUtil.positionFromBukkitLegacy(BukkitPlatformUtil.java:60) ~[SimpleCloud-NPC.jar:?]
[Lobby-1]       at eu.thesimplecloud.module.npc.plugin.npc.type.PlayerNPC.onSetup(PlayerNPC.kt:36) ~[SimpleCloud-NPC.jar:?]
[Lobby-1]       at eu.thesimplecloud.module.npc.plugin.npc.ServerNPCHandler.createNPCs(ServerNPCHandler.kt:45) ~[SimpleCloud-NPC.jar:?]
[Lobby-1]       at eu.thesimplecloud.module.npc.plugin.listener.CloudListener.updateNPCs(CloudListener.kt:31) ~[SimpleCloud-NPC.jar:?]
[Lobby-1]       at eu.thesimplecloud.module.npc.plugin.listener.CloudListener.handleUpdate$lambda$0(CloudListener.kt:21) ~[SimpleCloud-NPC.jar:?]
[Lobby-1]       at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
[Lobby-1]       at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
[Lobby-1]       at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1111) ~[paper-1.20.1.jar:git-Paper-196]
[Lobby-1]       at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
[Lobby-1]       at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by D151l** [comment]
Hello, could you send me the NPCs config?

**Comment by BadPackage** [comment]
Is't actually the default config. I'm on a non-static server and haven't specified any configuration for the NPC-Plugin.

**Comment by D151l** [comment]
Have you already created an NPC?

**Comment by BadPackage** [comment]
Nope.

**Comment by BadPackage** [comment]
I just checked, the error only occurs on non-static servers.

**Comment by D151l** [comment]
Ok, that's interesting. The "onSetup" metode is actually only triggered if an NPC exists.

**Comment by D151l** [comment]
Your "npcs" config in the Modules folder is empty, isn't it?

**Comment by BadPackage** [comment]
Oh! Looks like another admin made some NPCs in a world that does not exists anymore, and that's what's been causing the confusion. Thank you for your help <3
