### ISSUE TITLE
lobby server doesn't close

### ISSUE THREAD

**Issue by iazex** [theSimpleCloud/SimpleCloud#174]
when i join lobby 2 and then click on the npc then i can no longer go back to lobby 2

https://haste.simplecloud.app/toruparawo

**Comment by FllipEis** [comment]
Hey, I don't really understand the problem correctly. Could you describe it more clearly or maybe even record a small video where you show us your problem on the server 😄

**Comment by iazex** [comment]
es scheid jetzt zu gehen aber ich habe noch ein anders problem und zwar ist bei mir die tablist geht bei mir nicht

![image](https://github.com/theSimpleCloud/SimpleCloud/assets/68118798/9898b7eb-6375-4afa-801b-bb50a286a3a8)

**Comment by FllipEis** [comment]
Wie sieht deine config vom Proxy-Module aus? Es kann sein, dass du da den Namen von der Proxygruppe einmal anpassen musst

**Comment by iazex** [comment]
Ich habe da nicht viel verändert bisher

`{
  "proxyGroupConfigurations": [
    {
      "proxyGroup": "hub",
      "whitelist": [
        "Fllip",
        "Wetterbericht"
      ],
      "motds": {
        "firstLines": [
          "<gradient:#FFDE00:#FFFC00><bold>Scorcraft</bold></gradient> <dark_gray>»<gray> Back again? <dark_gray>|<bold><#4595ff> 1.12<#545454> - <#4595ff>1.19</bold>"
        ],
        "secondLines": [
          "<dark_gray>× <#178fff>Status<dark_gray>: <bold><#22cc22>Online</bold>"
        ],
        "playerInfo": [],
        "versionName": null
      },
      "maintenanceMotds": {
        "firstLines": [
          "<gradient:#FFDE00:#FFFC00><bold>Scorcraft</bold></gradient> <dark_gray>»<gray> Back again? <dark_gray>|<bold><#4595ff> 1.12<#545454> - <#4595ff>1.19</bold>"
        ],
        "secondLines": [
          "<dark_gray>× <#178fff>Status<dark_gray>: <bold><#c40000>Maintenance</bold>"
        ],
        "playerInfo": [],
        "versionName": "<dark_red><italic>Maintenance"
      }
    }
  ],
  "tablistConfigurations": [
    {
      "proxies": [
        "Proxy"
      ],
      "headers": [
        "<dark_gray>                                                                        <dark_gray>",
        "<aqua>SimpleCloud <dark_gray>» <gray>Simplify <white><italic>your</italic> <gray>network",
        "<dark_aqua>Online <dark_gray>» <gray>%ONLINE_PLAYERS%<dark_gray>/<gray>%MAX_PLAYERS% <dark_gray>┃ <dark_aqua>Server <dark_gray>» <gray>%DISPLAYNAME%",
        "<dark_gray>"
      ],
      "footers": [
        "<dark_gray>",
        "<dark_aqua>Twitter <dark_gray>» <gray>@theSimpleCloud",
        "<dark_aqua>Discord <dark_gray>» <gray>discord.gg/MPZs4h8",
        "<dark_aqua>Powered by <dark_gray>» <gray>Venocix.de",
        "<dark_gray>"
      ]
    }
  ],
  "maintenanceKickMessage": "<red>This service is in maintenance",
  "fullProxyKickMessage": "<red>This service is full"
}`

**Comment by FllipEis** [comment]
Ah okay, deine Proxygruppe heißt aber `Hub` du musst das dann in der Config überall einmal abändern

**Comment by iazex** [comment]
meine Proxygruppe heißt auch hub (ich hatte das um 4 uhr morgens gemacht)

**Comment by FllipEis** [comment]
Ja, das steht in der Dumpdatei drin, deswegen. Also wenn du das einmal anpasst, sollte es funktionieren 😄

**Comment by iazex** [comment]
oh jetzt habe ich es verstanden vielen dank :)

**Comment by iazex** [comment]
ich hätte nochmal ne kleine frage und zwar kann man auch einzele services machen ohne gruppe?
ich möchte einfach nur einen static server hinzufügen wo ich auch mal privat spielen kann

**Comment by iazex** [comment]
`[20:50:43] ERROR: eu.thesimplecloud.clientserverapi.lib.packet.exception.PacketException: An error occurred while attempting to handle packet: PacketIOCallEvent
        at eu.thesimplecloud.clientserverapi.lib.handler.packet.IncomingPacketHandler.handleQuery(IncomingPacketHandler.kt:65)
        at eu.thesimplecloud.clientserverapi.lib.handler.packet.IncomingPacketHandler.access$handleQuery(IncomingPacketHandler.kt:43)
        at eu.thesimplecloud.clientserverapi.lib.handler.packet.IncomingPacketHandler$handleIncomingPacket$1.invokeSuspend(IncomingPacketHandler.kt:50)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@333b1a13, Dispatchers.Default]
Caused by: eu.thesimplecloud.api.eventapi.exception.EventException: An error occurred while attempting to handle event eu.thesimplecloud.api.event.player.CloudPlayerLoginEvent
        at eu.thesimplecloud.api.eventapi.BasicEventManager$RegisteredEvent$Companion$fromEventMethod$1.execute(BasicEventManager.kt:130)
        at eu.thesimplecloud.api.eventapi.BasicEventManager.call(BasicEventManager.kt:61)
        at eu.thesimplecloud.base.manager.impl.EventManagerImpl.call(EventManagerImpl.kt:35)
        at eu.thesimplecloud.api.network.packets.event.PacketIOCallEvent.handle(PacketIOCallEvent.kt:39)
        at eu.thesimplecloud.clientserverapi.lib.handler.packet.IncomingPacketHandler.handleQuery(IncomingPacketHandler.kt:62)
        ... 8 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at eu.thesimplecloud.api.eventapi.BasicEventManager$RegisteredEvent$Companion$fromEventMethod$1.execute(BasicEventManager.kt:128)
        ... 12 more
Caused by: java.sql.SQLNonTransientConnectionException: (conn=301) execute() is called on closed connection
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
        at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeUpdate(ClientSidePreparedStatement.java:181)
        at eu.thesimplecloud.module.statistics.timed.store.SQLTimedValueStore.store(SQLTimedValueStore.kt:61)
        at eu.thesimplecloud.module.statistics.timed.listener.PlayerConnectListener.handle(PlayerConnectListener.kt:45)
        ... 17 more
Caused by: java.sql.SQLNonTransientConnectionException: execute() is called on closed connection
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.prolog(AbstractQueryProtocol.java:1889)
        at org.mariadb.jdbc.MariaDbStatement.executeQueryPrologue(MariaDbStatement.java:215)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:201)`
        
        es crashed leider doch wieder
