### ISSUE TITLE
PacketIOCallEvent

### ISSUE THREAD

**Issue by Fedox-die-Ente** [theSimpleCloud/SimpleCloud#179]
Nach einer gewissen Zeit fängt an die Cloud Probleme zu machen sobald man eine Instanz stoppt/startet.

Es folgt dieser Stacktrace:

`[16:14:54] ERROR: eu.thesimplecloud.clientserverapi.lib.packet.exception.PacketException: An error occurred while attempting to handle packet: PacketIOCallEvent
        at eu.thesimplecloud.clientserverapi.lib.handler.packet.IncomingPacketHandler.handleQuery(IncomingPacketHandler.kt:65)
        at eu.thesimplecloud.clientserverapi.lib.handler.packet.IncomingPacketHandler.access$handleQuery(IncomingPacketHandler.kt:43)
        at eu.thesimplecloud.clientserverapi.lib.handler.packet.IncomingPacketHandler$handleIncomingPacket$1.invokeSuspend(IncomingPacketHandler.kt:50)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@fd27250, Dispatchers.Default]
Caused by: eu.thesimplecloud.api.eventapi.exception.EventException: An error occurred while attempting to handle event eu.thesimplecloud.api.event.player.CloudPlayerLoginEvent
        at eu.thesimplecloud.api.eventapi.BasicEventManager$RegisteredEvent$Companion$fromEventMethod$1.execute(BasicEventManager.kt:130)
        at eu.thesimplecloud.api.eventapi.BasicEventManager.call(BasicEventManager.kt:61)
        at eu.thesimplecloud.base.manager.impl.EventManagerImpl.call(EventManagerImpl.kt:35)
        at eu.thesimplecloud.api.network.packets.event.PacketIOCallEvent.handle(PacketIOCallEvent.kt:39)
        at eu.thesimplecloud.clientserverapi.lib.handler.packet.IncomingPacketHandler.handleQuery(IncomingPacketHandler.kt:62)
        ... 8 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at eu.thesimplecloud.api.eventapi.BasicEventManager$RegisteredEvent$Companion$fromEventMethod$1.execute(BasicEventManager.kt:128)
        ... 12 more
Caused by: java.sql.SQLException: database connection closed
        at org.sqlite.SQLiteConnection.checkOpen(SQLiteConnection.java:429)
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:31)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:225)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
        at eu.thesimplecloud.module.statistics.timed.store.SQLiteTimedValueStore.store(SQLiteTimedValueStore.kt:58)
        at eu.thesimplecloud.module.statistics.timed.listener.PlayerConnectListener.handle(PlayerConnectListener.kt:45)
        ... 17 more`

Specs:
![image](https://github.com/theSimpleCloud/SimpleCloud/assets/67076970/4bbf16b8-01fe-49d5-b886-a2a7b4850563)

**Comment by JWeinelt** [comment]
Ich habe das exakt gleiche Problem.

**Comment by Fedox-die-Ente** [comment]
> Ich habe das exakt gleiche Problem.

Scheint vom dem Statistic Modul zu kommen, löschen sollte es dann erstmal auch lösen.

Ist ja jetzt nicht das wichtigste Modul

**Comment by FllipEis** [comment]
Statistics aren't currently being used. If we're going to use them again, this is going to be fixed, but until then, it's not.
