### ISSUE TITLE
Can't start Cloud

### ISSUE THREAD

**Issue by Dragontechreal** [theSimpleCloud/SimpleCloud#186]
I can't install the cloud / after installing the cloud it terminated the screen and there is a base error

`Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
        at eu.thesimplecloud.runner.RunnerClassLoaderInitMainKt.getCloudVersion(RunnerClassLoaderInitMain.kt:95)
        at eu.thesimplecloud.runner.RunnerClassLoaderInitMainKt.<clinit>(RunnerClassLoaderInitMain.kt:42)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 2 more`

**Comment by DevSnx** [comment]
Java & Screen installed?

**Comment by Dragontechreal** [comment]
Yes

**Comment by Dragontechreal** [comment]
The cloud has loaded the dependencies but after that it was offline and the error is coming

**Comment by DevSnx** [comment]
send the full log please

**Comment by Dragontechreal** [comment]
where can i find the full log?

**Comment by Dragontechreal** [comment]
Works now
