### ISSUE TITLE
You're not registered on the network

### ISSUE THREAD

**Issue by Dragontechreal** [theSimpleCloud/SimpleCloud#187]
Sometimes after I disconnect from my Devserver and want to rejoin i can't join because of the message "You are not registered on the Network!". At the same time in the server console of the devserver there is an error in the console. After I restart the server it works.
```
[Devserver-1][18:40:42 WARN]: Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalStateException: zip file closed
[Devserver-1][18:40:42 WARN]:  at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846)
[Devserver-1][18:40:42 WARN]:  at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338)
[Devserver-1][18:40:42 WARN]:  at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516)
[Devserver-1][18:40:42 WARN]:  at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
[Devserver-1][18:40:42 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[Devserver-1][18:40:42 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[Devserver-1][18:40:42 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[Devserver-1][18:40:42 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[Devserver-1][18:40:42 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[Devserver-1][18:40:42 WARN]:  at SimpleCloud-Plugin.jar//kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:146)
[Devserver-1][18:40:42 WARN]:  at SimpleCloud-Plugin.jar//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:117)
[Devserver-1][18:40:42 WARN]:  at SimpleCloud-Plugin.jar//kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
[Devserver-1][18:40:42 WARN]:  at SimpleCloud-Plugin.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
[Devserver-1][18:40:42 WARN]:  at SimpleCloud-Plugin.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
[Devserver-1][18:40:42 WARN]:  at SimpleCloud-Plugin.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
[Devserver-1][18:40:43 INFO]: UUID of player _Dragontech_ is f4a27722-3f0f-494c-9f78-e4cb28b8c526
```

**Comment by FllipEis** [comment]
Which Minecraft server version and cloud version are you using?

**Comment by Dragontechreal** [comment]
I use Cloud Version 2.7.1 and my Minecraft Server Version is paper 1.20.5

**Comment by FllipEis** [comment]
How many times is this happening?

**Comment by Dragontechreal** [comment]
Everytime, after a restart of the devserver i can join but can't reconnect without restarting the devserver

**Comment by FllipEis** [comment]
Are there any other errors? Are you using mongo or sql?

**Comment by Dragontechreal** [comment]
No there aren't any other errors and i'm using sql
There is sometimes another error in the normal cloud console when i join the network and not the specific server but i don't have that error at the moment

**Comment by FllipEis** [comment]
Okay, just give me the error when it comes up again. Also we can help you a lot faster, if you create an issue on our [Discord](https://discord.gg/MPZs4h8)

**Comment by FllipEis** [comment]
Closed due to inactivity
