### ISSUE TITLE
Unable to run simplecloud

### ISSUE THREAD

**Issue by cnluminous** [theSimpleCloud/SimpleCloud#188]
It seems that there is a problem with the storage server, which makes it impossible to obtain dependencies normally.

<details><summary>log</summary>
<p>

```java
C:\Users\CNLuminous\Downloads\SimpleCloud-v2.7.1>java -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:CompileThreshold=100 -XX:+UnlockExperimentalVMOptions -XX:+UseCompressedOops -Xmx512m -Xms256m -jar runner.jar
Deleting dependencies directory...
Loading dependencies...
Loading dependencies: clientserverapi-4.1.18, commons-lang3-3.12.0, slf4j-nop-1.7.32, jansi-2.4.1, jline-3.23.0, kmongo-4.10.0, commons-io-2.14.0, slf4j-simple-1.7.32, guava-32.1.3-jre, kotlinx-coroutines-core-1.7.3, gson-2.10.1, netty-all-4.1.100.Final, reflections-0.10.2, mariadb-java-client-2.7.4, clikt-2.8.0, adventure-api-4.14.0, adventure-text-serializer-gson-4.14.0, sqlite-jdbc-3.43.2.1
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at eu.thesimplecloud.runner.RunnerClassLoaderInitMainKt.executeDependencyLoaderMain(RunnerClassLoaderInitMain.kt:106)
        at eu.thesimplecloud.runner.RunnerClassLoaderInitMainKt.main(RunnerClassLoaderInitMain.kt:83)
Caused by: java.lang.IllegalArgumentException: No valid repository was found for clientserverapi-4.1.18 repos: [https://repo.maven.apache.org/maven2/, https://repo.thesimplecloud.eu/artifactory/gradle-release-local/]
        at eu.thesimplecloud.loader.dependency.AdvancedDependencyDownloader.downloadFiles(AdvancedDependencyDownloader.kt:51)
        at eu.thesimplecloud.loader.dependency.DependencyLoader.resolveDependencyFilesIfNotExist(DependencyLoader.kt:91)
        at eu.thesimplecloud.loader.dependency.DependencyLoader.collectSubDependencies(DependencyLoader.kt:82)
        at eu.thesimplecloud.loader.dependency.DependencyLoader.collectSubDependencies$default(DependencyLoader.kt:74)
        at eu.thesimplecloud.loader.dependency.DependencyLoader.loadDependencies(DependencyLoader.kt:59)
        at eu.thesimplecloud.loader.dependency.LauncherDependencyLoader.loadLauncherDependencies(LauncherDependencyLoader.kt:33)
        at eu.thesimplecloud.loader.dependency.DependencyLoaderMainKt.main(DependencyLoaderMain.kt:38)
        ... 6 more
``` 

</p>
</details> 

I tried ping the website repo.theimplecloud.eu and found that he was impassable,Also I tried to use tcp.ping.pe/ to test the website, the same is not working

**Comment by cnluminous** [comment]
I accidentally typed the wrong tittle name, haha

**Comment by ImLisaa** [comment]
The reason it was not working was, that the repository required for downloading was offline. Try again now, it's back online.

**Comment by cnluminous** [comment]
It can work now
