### ISSUE TITLE
ERROR: java.lang.NullPointerException: failed to find service version WATERFALL

### ISSUE THREAD

**Issue by PizzaWunsch** [theSimpleCloud/SimpleCloud#192]
Folgender Fehler tritt auf, wenn ich die Cloud starten möchte. Habe eigentlich nichts angefasst und andere meinen auch nichts gemacht zu haben. Woran könnte es liegen?
`
[12:10:02] CONSOLE: Das Modul SimpleCloud-Rest von Wetterbericht wurde geladen
[12:10:02] CONSOLE: Das Modul SimpleCloud-InternalWrapper von Wetterbericht wurde geladen
[12:10:02] CONSOLE: Das Modul SimpleCloud-Notify von Fllip wurde geladen
[12:10:02] CONSOLE: Das Modul SimpleCloud-Proxy von Fllip wurde geladen
[12:10:03] ERROR: java.lang.NullPointerException: failed to find service version WATERFALL
        at eu.thesimplecloud.api.servicegroup.impl.AbstractServiceGroup.getServiceVersion(AbstractServiceGroup.kt:133)
        at eu.thesimplecloud.base.manager.service.ServiceHandler.startService(ServiceHandler.kt:81)
        at eu.thesimplecloud.base.manager.service.ServiceHandler.startServicesByGroup(ServiceHandler.kt:57)
        at eu.thesimplecloud.base.manager.service.ServiceHandler.queueMinServices(ServiceHandler.kt:122)
        at eu.thesimplecloud.base.manager.service.ServiceHandler.access$queueMinServices(ServiceHandler.kt:43)
        at eu.thesimplecloud.base.manager.service.ServiceHandler$startThread$1.invoke(ServiceHandler.kt:156)
        at eu.thesimplecloud.base.manager.service.ServiceHandler$startThread$1.invoke(ServiceHandler.kt:150)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
`

**Comment by Panda260** [comment]
Hey
im neuen update wurden die Namen der Versionen angepasst, es gibt Einzellfälle wu der name in der gruppen configuration nicht angepasst wurde dort musst du den dann einmal manuell umbenennen, von WATERFALL -> WATERFALL_1_21 und anschließen die Cloud neu starten

**Comment by PizzaWunsch** [comment]
läuft, vielen Dank! :)

**Comment by PizzaWunsch** [comment]
WATERFALL -> WATERFALL_1_21 in Cloud/groups/proxies hat es behoben.
