### ISSUE TITLE
Unerwartete Fehler 

### ISSUE THREAD

**Issue by PizzaWunsch** [theSimpleCloud/SimpleCloud#193]
`[12:19:12] [INFO]: [SimpleCloud-Plugin] Enabling SimpleCloud-Plugin v1.0
[12:19:12] [ERROR]: Error occurred while enabling SimpleCloud-Plugin v1.0 (Is it up to date?)
kotlin.UninitializedPropertyAccessException: lateinit property instance has not been initialized
	at eu.thesimplecloud.api.CloudAPI$Companion.getInstance(CloudAPI.kt:61) ~[?:?]
	at eu.thesimplecloud.plugin.startup.CloudPlugin.thisService(CloudPlugin.kt:122) ~[?:?]
	at eu.thesimplecloud.plugin.startup.CloudPlugin.onEnable(CloudPlugin.kt:132) ~[?:?]
	at eu.thesimplecloud.plugin.server.CloudSpigotPlugin.onEnable(CloudSpigotPlugin.kt:53) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:322) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:389) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(SourceFile:440) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(SourceFile:399) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(SourceFile:516) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(SourceFile:441) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(SourceFile:409) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:389) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:744) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_422]
`

Moin, ich habe hin und wieder mal das Problem, dass diese Fehlermeldung kommt. Ich gehe davon aus, dass das vielleicht auch am Update liegen könnte. Gibt es vielleicht ein link, in der man sich die neusten Module-Versionen ziehen kann? :D

Vielen dank schonmal

**Comment by PizzaWunsch** [comment]
Ich merke gerade, dass das natürlich nichts mit den Modulen zu tun hat, aber ich kann mir den Fehler dennoch nicht erklären.
Man kann zudem bei diesen Fehler auch nicht den Server betreten

**Comment by PizzaWunsch** [comment]
Liegt anscheiend an eines meiner Plugins, im sorry.
