### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by InvisibleMalte** [theSimpleCloud/SimpleCloud#198]
```
[04:23:43] CONSOLE: Der Spieler ********** hat die Verbindung getrennt. (********-****-****-****-************/***.***.***.***)
[04:23:43] ERROR: eu.thesimplecloud.clientserverapi.lib.packet.exception.PacketException: An error occurred while attempting to handle packet: PacketIOCallEvent
        at eu.thesimplecloud.clientserverapi.lib.handler.packet.IncomingPacketHandler.handleQuery(IncomingPacketHandler.kt:65)
        at eu.thesimplecloud.clientserverapi.lib.handler.packet.IncomingPacketHandler.access$handleQuery(IncomingPacketHandler.kt:43)
        at eu.thesimplecloud.clientserverapi.lib.handler.packet.IncomingPacketHandler$handleIncomingPacket$1.invokeSuspend(IncomingPacketHandler.kt:50)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1fab50cc, Dispatchers.Default]
Caused by: eu.thesimplecloud.api.eventapi.exception.EventException: An error occurred while attempting to handle event eu.thesimplecloud.api.event.player.CloudPlayerLoginEvent
        at eu.thesimplecloud.api.eventapi.BasicEventManager$RegisteredEvent$Companion$fromEventMethod$1.execute(BasicEventManager.kt:130)
        at eu.thesimplecloud.api.eventapi.BasicEventManager.call(BasicEventManager.kt:61)
        at eu.thesimplecloud.base.manager.impl.EventManagerImpl.call(EventManagerImpl.kt:35)
        at eu.thesimplecloud.api.network.packets.event.PacketIOCallEvent.handle(PacketIOCallEvent.kt:39)
        at eu.thesimplecloud.clientserverapi.lib.handler.packet.IncomingPacketHandler.handleQuery(IncomingPacketHandler.kt:62)
        ... 8 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at eu.thesimplecloud.api.eventapi.BasicEventManager$RegisteredEvent$Companion$fromEventMethod$1.execute(BasicEventManager.kt:128)
        ... 12 more
Caused by: java.sql.SQLNonTransientConnectionException: (conn=18851) execute() is called on closed connection
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
        at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeUpdate(ClientSidePreparedStatement.java:181)
        at eu.thesimplecloud.module.statistics.timed.store.SQLTimedValueStore.store(SQLTimedValueStore.kt:61)
        at eu.thesimplecloud.module.statistics.timed.listener.PlayerConnectListener.handle(PlayerConnectListener.kt:45)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 14 more
Caused by: java.sql.SQLNonTransientConnectionException: execute() is called on closed connection
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.prolog(AbstractQueryProtocol.java:1889)
        at org.mariadb.jdbc.MariaDbStatement.executeQueryPrologue(MariaDbStatement.java:215)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:201)
        ... 19 more
```

**Comment by InvisibleMalte** [comment]
"Moin, aus /modules/ die `SimpleCloud-Statistics.jar` löschen und Cloud neustarten"
~ulfgerstenkorn

(Antwort auf Discord - https://discord.com/channels/605843163013316634/1314796991468933131/1314796991468933131)
