### ISSUE TITLE
Trotz aktivierten if forwarding - If you wish to use IP forwarding, please enable it in your BungeeCord config as well!

### ISSUE THREAD

**Issue by BrianTL4** [theSimpleCloud/SimpleCloud#32]
ich habe ein Problem hiermit 

`02:23:06 [WARNING] Error dispatching event ServerKickEvent(cancelled=false, player=BRBrianTL4, kickedFrom=BungeeServerInfo(name=Lobby-1, socketAddress=/45.88.109.229:50000, restricted=false), kickReasonComponent=[TranslatableComponent(format=%(?:(\d+)\$)?([A-Za-z%]|$), translate=If you wish to use IP forwarding, please enable it in your BungeeCord config as well!, with=null)], cancelServer=null, state=CONNECTING) to listener eu.thesimplecloud.plugin.proxy.bungee.listener.BungeeListener@5178345d
java.lang.NullPointerException
	at eu.thesimplecloud.api.player.AbstractCloudPlayerManager$updater$1.determineEventsToCall(AbstractCloudPlayerManager.kt:63)
	at eu.thesimplecloud.api.player.AbstractCloudPlayerManager$updater$1.determineEventsToCall(AbstractCloudPlayerManager.kt:40)
	at eu.thesimplecloud.api.cachelist.ICacheList$DefaultImpls.update(ICacheList.kt:43)
	at eu.thesimplecloud.api.cachelist.AbstractCacheList.update(AbstractCacheList.kt:30)
	at eu.thesimplecloud.plugin.impl.player.AbstractServiceCloudPlayerManager.update(AbstractServiceCloudPlayerManager.kt:43)
	at eu.thesimplecloud.plugin.impl.player.AbstractServiceCloudPlayerManager.update(AbstractServiceCloudPlayerManager.kt:40)
	at eu.thesimplecloud.api.cachelist.ICacheList$DefaultImpls.update$default(ICacheList.kt:40)
	at eu.thesimplecloud.api.player.ICloudPlayer$DefaultImpls.update(ICloudPlayer.kt:209)
	at eu.thesimplecloud.api.player.CloudPlayer.update(CloudPlayer.kt:35)
	at eu.thesimplecloud.plugin.proxy.ProxyEventHandler.handleServerKick(ProxyEventHandler.kt:209)
	at eu.thesimplecloud.plugin.proxy.bungee.listener.BungeeListener.on(BungeeListener.kt:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:399)
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:341)
	at net.md_5.bungee.protocol.packet.Kick.handle(Kick.java:35)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
02:23:06 [INFO] [BRBrianTL4] disconnected with: §cKicked whilst connecting to Lobby-1: §fIf you wish to use IP forwarding, please enable it in your BungeeCord config as well!
02:23:06 [INFO] [Geyser-BungeeCord] BrianTL4 has disconnected from remote Java server on address 45.88.109.229 because of §r§cKicked whilst connecting to Lobby-1: §r§fIf you wish to use IP forwarding, please enable it in your BungeeCord config as well!
02:23:06 [INFO] [BRBrianTL4] -> UpstreamBridge has disconnected
02:23:06 [INFO] [BRBrianTL4] <-> ServerConnector [Lobby-1] has disconnected
02:23:06 [INFO] [Geyser-BungeeCord] Bedrock user with ip: /80.187.118.208 has disconnected for reason CLOSED_BY_REMOTE_PEER`

`ip forward = true`

es könnte aber Probleme mit den Plugin [GeyserMC](https://geysermc.org/) geben

währe schön wenn ihr das hinbekommt, weil dann ist es möglich Bedrock und Java Spieler auf einen Java Server zu holen

**Comment by Wetterbericht** [comment]
Es sieht so aus als würdest du einen Geyser-Proxy verwenden. Dieser Proxy wird allerdings nicht offiziell unterstützt. Wenn du es schaffst den Fehler mit einem normalen Bungeecord zu reproduzieren kannst du dich gerne nochmal melden.
